import java.lang.*;
public class exceptions{
    public static void main(String Args[]){4
        int[] array = new int[3];

        try{
06
            for(int i=0;i<4;++i){
07
                array[i] = i;
08
            }
09
            System.out.println(array);
10
        }
11
        catch(ArrayIndexOutOfBoundsException e){
12
            System.out.println("filIn: " + e.fillInStackTrace());
13
            System.out.println("cause: " + e.getCause());
14
            System.out.println("local: " + e.getLocalizedMessage());
15
            System.out.println("messa: " + e.getMessage());
16
            System.out.println("trace: " + e.getStackTrace());
17
            System.out.println();
18
            System.out.println();
19
            System.out.print("trace: "); e.printStackTrace();
20
            System.out.println();
21
            System.out.print("string: ");e.toString();
22
            System.out.println();
23
            System.out.println();
24
25
            System.out.println("Oops, we went to far, better go back to 0!");
26
            throw (Exception) new Exception().initCause(e);
27
        }
28
        finally{
29
            System.out.println(array);
30
31
        }
32
    }
33
}
